name: Docker CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build Docker image
        run: docker build -t app:test .

      - name: Run Docker container
        run: |
          # Run the container in detached mode
          docker compose up -d
          
          # Wait for a few seconds to ensure the container is up and running
          sleep 20

          # Test the application endpoint
          curl -f http://localhost:8090/actuator/health || exit 1

          # Stop and remove the container
          docker compose down